//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKASHTICKETPROJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl()
        {
            this.tbl_Tickets = new HashSet<tbl_Tickets>();
        }
    
        public int RowID { get; set; }
        public string SID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerArea { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerContactPerson { get; set; }
        public string CostomerMobile { get; set; }
        public string Referral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Tickets> tbl_Tickets { get; set; }
    }
}
