//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKASHTICKETPROJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tickets
    {
        public int TicketID { get; set; }
        public int RowID { get; set; }
        public string Ticket_Type { get; set; }
        public string Ticket_Subject { get; set; }
        public string Ticket_Description { get; set; }
        public string Ticket_Status { get; set; }
    
        public virtual tbl tbl { get; set; }
    }
}
